// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH974PjdgBaKGBkcIwY193ZwSBHUtT6io',
    appId: '1:25562066670:web:ebd465cc91aac86cf78dff',
    messagingSenderId: '25562066670',
    projectId: 'pawtroli-a54e4',
    authDomain: 'pawtroli-a54e4.firebaseapp.com',
    storageBucket: 'pawtroli-a54e4.firebasestorage.app',
    measurementId: 'G-CT3PK52VLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB63CwFT3IL4S0eJ0l8mYc5jgscgCJyoGc',
    appId: '1:25562066670:android:dc8bc5a1f4fbb581f78dff',
    messagingSenderId: '25562066670',
    projectId: 'pawtroli-a54e4',
    storageBucket: 'pawtroli-a54e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRJI-YPbI14oD11OJSvKAJUEv-beVZIA',
    appId: '1:25562066670:ios:aa16e19df6314bb8f78dff',
    messagingSenderId: '25562066670',
    projectId: 'pawtroli-a54e4',
    storageBucket: 'pawtroli-a54e4.firebasestorage.app',
    iosBundleId: 'com.example.pawtroli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRJI-YPbI14oD11OJSvKAJUEv-beVZIA',
    appId: '1:25562066670:ios:aa16e19df6314bb8f78dff',
    messagingSenderId: '25562066670',
    projectId: 'pawtroli-a54e4',
    storageBucket: 'pawtroli-a54e4.firebasestorage.app',
    iosBundleId: 'com.example.pawtroli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH974PjdgBaKGBkcIwY193ZwSBHUtT6io',
    appId: '1:25562066670:web:383a7f30b34d39a4f78dff',
    messagingSenderId: '25562066670',
    projectId: 'pawtroli-a54e4',
    authDomain: 'pawtroli-a54e4.firebaseapp.com',
    storageBucket: 'pawtroli-a54e4.firebasestorage.app',
    measurementId: 'G-Q3YE6PKKTG',
  );
}
